name: Generate and publish docs

on:
  push:
    branches:
      - main
      - docs-build
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Get repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx myst-parser git+https://github.com/antmicro/sphinx_antmicro_theme
    - name: Generate the docs
      run: |
        cd docs
        make html
