name: Generate and publish docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  docs:
    runs-on: ubuntu-latest
    steps:

      - name: Get repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Generate the docs
        run: |
          cd docs
          make SPHINXOPTS="-A commit=$GITHUB_SHA -A branch=$GITHUB_REF_NAME" html latexpdf
          cp build/latex/*.pdf build/html/

      - name: 'Upload artifact: Sphinx HTML and PDF'
        uses: actions/upload-artifact@v3
        with:
          name: Documentation
          path: docs/build/html

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cd docs/build/html
          touch .nojekyll
          git init
          cp ../../../.git/config ./.git/config
          git add .
          git config --local user.email "push@gha"
          git config --local user.name "GHA"
          git commit -am "update ${{ github.sha }}"
          git push -u origin +HEAD:gh-pages
          rm -rf .git
