name: Generate and publish docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  docs:
    runs-on: ubuntu-latest
    steps:

      - name: Get repository
        uses: actions/checkout@v3

      - uses: docker://btdi/sphinx:min
        with:
          args: ./.github/scripts/sphinx.sh

      - uses: docker://btdi/latex
        with:
          args: ./.github/scripts/latex.sh

      - name: 'Upload artifact: Sphinx HTML and PDF'
        uses: actions/upload-artifact@v3
        with:
          name: Documentation
          path: docs/build/html

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          sudo chown -R $(whoami) docs
          cd docs/build/html
          touch .nojekyll
          git init
          cp ../../../.git/config ./.git/config
          git add .
          git config --local user.email "push@gha"
          git config --local user.name "GHA"
          git commit -am "update ${{ github.sha }}"
          git push -u origin +HEAD:gh-pages
          rm -rf .git
