name: Running Python CI jobs

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  python-run:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install yapf pytest pytest-cov
      - name: Lint with yapf
        run: |
          ./.github/check_code_formatting.sh
      - name: Test with pytest
        run: |
          ./.github/run_tests.sh
  installation-test:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Show help
        run: |
          # we should be able to execute from any directory now
          cd /tmp/
          raviewer --help
